apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: actions-runner-system
spec:
  interval: 5m
  targetNamespace: actions-runner-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: arc-charts
        namespace: actions-runner-system
