apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-kube-mode
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-runner-kube-mode
  namespace: actions-runner-system
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log","pods/exec","secrets"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","create","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-kube-mode
  namespace: actions-runner-system
subjects:
  - kind: ServiceAccount
    name: gha-runner-kube-mode
    namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gha-runner-kube-mode