apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-tauri
  namespace: actions-runner-system
spec:
  interval: 5m
  dependsOn:
    - name: gha-runner-scale-set-controller
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: arc-charts
        namespace: actions-runner-system
  values:
    githubConfigUrl: https://github.com/rahanahu/first-tauri
    githubConfigSecret: gha-github-config

    # Workflow で指定する runs-on ラベル名
    runnerScaleSetName: github-actions-runner

    # とりあえず最小
    minRunners: 1
    maxRunners: 4

    # Kubernetes mode を有効化（work は ephemeral PVC）
    containerMode:
      type: "kubernetes"
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 5Gi

    # RBACを付けた SA 
    template:
      spec:
        securityContext:
          fsGroup: 123
        serviceAccountName: gha-runner-kube-mode
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s/index.js
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"

